name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: linux-x64
            binary_name: log-time-slicer
          - os: windows-latest
            target: windows-x64
            binary_name: log-time-slicer.exe

    outputs:
      binary_name: ${{ steps.set-output.outputs.binary_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build binary
      run: |
        pyinstaller --onefile main.py --name ${{ matrix.binary_name }}
      env:
        TARGET: ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.binary_name }}
        path: dist/${{ matrix.binary_name }}

    - name: Set output
      id: set-output
      run: echo "::set-output name=binary_name::${{ matrix.binary_name }}"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.binary_name }}
        path: ./dist

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/${{ needs.build.outputs.binary_name }}
        asset_name: ${{ needs.build.outputs.binary_name }}
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
